name: CD

on:
  push:
    branches:
    - master
    - support/*
    paths-ignore:
    - 'docs/**'
    - 'README.md'
    - '.editorconfig'
    - '.gitattributes'
    - '.gitignore'
    - '.github/ISSUE_TEMPLATE/**'
    - '.github/pull_request_template.md'

defaults: *default-defaults

jobs:
  build:
    name: 'Build & Test'
    runs-on: ubuntu-latest
    steps:
    - *checkout
    - *setup-dotnet
    - *restore
    - *build
    - *test
    - *pack
    - *publish-codecov
    - *upload-artifacts
  build-standalone-binaries: *build-standalone-binaries
  mutation-tests:
    name: 'Mutation Test'
    needs: build
    runs-on: windows-latest
    steps:
    - *checkout
    - *setup-dotnet
    - *mutation-test
    - *mutation-test-archive
    - *mutation-test-upload-artifacts
  integration-tests:
    name: 'Integration Tests'
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
    steps:
    - *checkout
    - *setup-dotnet
    - *run-integration-tests
  publish:
    name: 'Publish'
    needs:
    - build
    - build-standalone-binaries
    - integration-tests
    runs-on: ubuntu-latest
    steps:
    - *checkout
    - *setup-dotnet
    - *setup-nuget
    - *download-artifacts
    - *publish-github
