name: CI

on:
  pull_request:
    branches:
    - master
    - support/*
    paths-ignore:
    - 'docs/**'
    - 'README.md'
    - '.editorconfig'
    - '.gitattributes'
    - '.gitignore'
    - '.github/ISSUE_TEMPLATE/**'
    - '.github/pull_request_template.md'

defaults: *default-defaults

jobs:
  build:
    name: 'Build & Test'
    runs-on: ubuntu-24.04
    steps:
    - *checkout
    - *setup-dotnet
    - *setup-openssl
    - *restore
    - *build
    - *test
    - *pack
    - *publish-codecov
    - *upload-artifacts
  build-standalone-binaries: *build-standalone-binaries
  mutation-tests:
    name: 'Mutation Test'
    needs: build
    runs-on: windows-latest
    steps:
    - *checkout
    - *setup-dotnet
    - *setup-openssl
    - *mutation-test
    - *mutation-test-archive
    - *mutation-test-upload-artifacts
  integration-tests:
    name: 'Integration Tests'
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-13]
    steps:
    - *checkout
    - *setup-dotnet
    - *setup-openssl
    - *run-integration-tests
