#<shared>

definitions:
  default-defaults: &default-defaults
    run:
      shell: bash

  checkout: &checkout
    uses: actions/checkout@v2
    with:
      fetch-depth: '0'

  setup-dotnet: &setup-dotnet
    name: Setup .NET
    uses: actions/setup-dotnet@v3
    with:
      dotnet-version: |
        3.1.x
        5.0.x
        6.x
        7.x

  setup-nuget: &setup-nuget
    name: Setup NuGet
    run: |
      dotnet nuget update source github --store-password-in-clear-text --username AshleighAdams --password ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      dotnet nuget enable source github

  restore: &restore
    name: Restore
    run: dotnet restore

  build: &build
    name: Build
    run: dotnet build --configuration Release --no-restore
    
  test: &test
    name: Test
    run: dotnet test --configuration Debug --logger GitHubActions -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura

  mutation-test: &mutation-test
    name: Mutation Test
    run: |
      dotnet tool install --global dotnet-stryker --version 3.2.0
      cd tests/UnitTests
      if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
        dotnet stryker --reporter html --reporter dashboard --reporter progress --version master --log-to-file
      else
        dotnet stryker --reporter html --reporter progress --log-to-file
      fi
    env:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  mutation-test-archive: &mutation-test-archive
    name: Archive mutation output
    if: success() || failure()
    run: |
      cd tests/UnitTests
      mkdir -p ../../artifacts
      find StrykerOutput -name mutation-report.html -exec cp {} ../../artifacts/ \;
      if [[ -d StrykerOutput ]]; then
        mv StrykerOutput ../../artifacts/StrykerOutput
      fi

  publish-codecov: &publish-codecov
    name: Publish Codecov
    uses: codecov/codecov-action@v2
    with:
      token: ${{ secrets.CODECOV_TOKEN }}
      files: ./tests/UnitTests/coverage.cobertura.xml

  pack: &pack
    name: Pack
    run: dotnet pack -o artifacts --configuration Release --no-restore

  upload-artifacts: &upload-artifacts
    name: Upload Artifacts
    uses: actions/upload-artifact@v2
    if: success() || failure()
    with:
      name: artifacts
      path:  |
        artifacts/*

  download-artifacts: &download-artifacts
    name: Download Artifacts
    uses: actions/download-artifact@v2

  publish-github: &publish-github
    name: Publish Nuget GitHub
    run: dotnet nuget push 'artifacts/*.nupkg' -k ${GITHUB_TOKEN} -s github --skip-duplicate --no-symbols
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-integration-tests: &run-integration-tests
    name: Run Integration Tests
    run: |
      chmod +x ./tests/IntegrationTests/run.sh
      ./tests/IntegrationTests/run.sh

  empty: "hi" # fixes the yml parser from messing the last value up

#</shared>
